
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: hw11_fastapi.db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dinamo12
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"