"""Add avatar column to clients_table

Revision ID: 00c7169cac3a
Revises: 0d6dd8b10436
Create Date: 2024-01-25 10:51:47.216415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c7169cac3a'
down_revision: Union[str, None] = '0d6dd8b10436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_table', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients_table', 'avatar')
    # ### end Alembic commands ###
